backend:
  name: github
  repo: efesolutions24-alt/electra-frame-website
  branch: main
  base_url: https://api.github.com

media_folder: ""
public_folder: "/"

collections:
  - name: "projects"
    label: "Projects"
    folder: ""
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "text" }
